modLoader="javafml"
loaderVersion="[4,)"
license="AGPL-3.0"

[[mods]]
modId="minecraftlocalizationfileschecker"
version="${file.jarVersion}"
displayName="Minecraft Localization Files Checker"
authors="Misaka_10571"
description="A simple mod that helps to check if necessary files are installed correctly through config file."

[[dependencies.minecraftlocalizationfileschecker]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.minecraftlocalizationfileschecker]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"